app:
  server-url: http://localhost:8080
  bot-name: 阿尔法猪

platform:
  ntchat:
    bot-wxid:
    admin-wxid:
    guid:
    api-url: http://127.0.0.1:8000
  wxbot:
    bot-wxid:
    admin-wxid:
    api-url: http://127.0.0.1:18080

plugin:
  translator:
    baidu:
      app-id:
      app-key:
    wxapp:
      guid:
  gpt:
    moonshot:
      api-key-list:
        - key1
        - key2
    coze:
      normal-bot:
        bot-id: 111
        access-token: 222
      fuck-bot:
        bot-id: 333
        access-token: 444
  keywordreminder:
    keyword-list:
      - 关键词1
      - 关键词2
      # 带有特殊符号要加引号
      - "[猪头]"

cron:
  weibo:
    ganggang-wxid-list:
      - wxid1
      - wxid2

  bilibili:
    chuangge-wxid-list:
      - wxid1
      - wxid2
