app:
  server-url: http://localhost:8080
  bot-name: my-bot

platform:
  ntchat:
    bot-wxid:
    admin-wxid:
    guid:
    api-url: http://127.0.0.1:8000
  wxbot:
    bot-wxid: wxid_u3678r4hvlok12
    admin-wxid:
    api-url: http://127.0.0.1:18080

plugin:
  translator:
    baidu:
      app-id:
      app-key:
  gpt:
    moonshot:
      api-key-list:
        - key1
        - key2
  keywordreminder:
    keyword-regex: "这个关键词会提醒|helloworld"

cron:
  weibo:
    ganggang-wxid-list:
      - wxid1
      - wxid2

  bilibili:
    chuangge-wxid-list:
      - wxid1
      - wxid2
